http:
  routers:
    cockpit:
      rule: Host(`cockpit-sc.alvesm.dev`)
      entryPoints:
        - websecure
      service: cockpit
      middlewares:
        - default-ipallowlist
      tls:
        certResolver: letsencrypt
  services:
    cockpit:
      loadBalancer:
        servers:
          - url: https://192.168.100.151:9090
  middlewares:
    default-ipallowlist:
      ipAllowList:
        sourceRange:
          - "192.168.100.0/24"

tls:
  stores:
    default:
      defaultGeneratedCert:
        resolver: letsencrypt
        domain:
          main: alvesm.dev
          sans:
            - portainer-sc.alvesm.dev
            - jellyfin-sc.alvesm.dev
            - qbittorrent-sc.alvesm.dev
            - radarr-sc.alvesm.dev
            - prowlarr-sc.alvesm.dev
            - bazarr-sc.alvesm.dev
            - jellyseerr-sc.alvesm.dev
            - sonarr-sc.alvesm.dev
            - grafana-sc.alvesm.dev
            - cockpit-sc.alvesm.dev
            - autokube-sc.alvesm.dev
