# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "i2c-dev"
    "i2c-piix4"
    "kvm-amd"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/534ebef1-ca48-48a0-bcf5-3e081460d4e8";
    fsType = "xfs";
  };

  boot.initrd.luks.devices."nixos-rootfs" = {
    device = "/dev/disk/by-path/pci-0000:01:00.0-nvme-1";
    header = "/dev/disk/by-partuuid/d3a16764-9496-4c51-b708-7857493e2412";
    keyFile = "/key/usb-luks.key";
    fallbackToPassword = true;
    allowDiscards = true;
    preOpenCommands = ''
      mkdir -p /key
      sleep 3
      mount -n -t ext4 -o ro /dev/disk/by-uuid/ccab8878-6047-4e1a-a212-426f917752a8 /key || echo "USB not found"
    '';
    postOpenCommands = ''
      umount /key 2>/dev/null || true
      rm -rf /key
    '';
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-partuuid/d95a329c-a5f3-4e7f-8b95-89b932bef26f";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/myexternaldisk" = {
    device = "/dev/disk/by-uuid/5db6bbf9-6356-4ac9-a561-195be32338b3";
    fsType = "ext4";
    options = [
      "noatime"
      "nodiratime"
      "commit=60"
      "x-gvfs-show"
    ];
  };

  systemd.tmpfiles.rules = [
    "d /mnt/myexternaldisk 0755 marcelo users -"
  ];

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
