# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "i2c-dev"
    "i2c-piix4"
    "kvm-amd"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/454f9dc0-3f81-439b-8d26-8bcbc6e4b396";
    fsType = "xfs";
  };

  boot.initrd.luks.devices."nixos-rootfs".device =
    "/dev/disk/by-uuid/6fa9ae8d-6cc2-4a71-b1d3-83e3eb4a62d7";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6B94-6B59";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/myexternaldisk" = {
    device = "/dev/disk/by-uuid/5db6bbf9-6356-4ac9-a561-195be32338b3";
    fsType = "ext4";
    options = [
      "noatime"
      "nodiratime"
      "commit=60"
      "x-gvfs-show"
    ];
  };

  systemd.tmpfiles.rules = [
    "d /mnt/myexternaldisk 0755 marcelo users -"
  ];

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
